services:
  wireguard:
    image: procustodibus/wireguard
    volumes:
    - ./conf/wg0.conf:/etc/wireguard/wg0.conf
    env_file:
      - ./.env
    ports:
      - 9091:9091/tcp
      - 51821:51820
    restart: always
  transmission:
    image: linuxserver/transmission:4.0.6
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    env_file:
      - ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - $WORKDIR/transmission-config:/config
      - $WORKDIR/downloads:/downloads
      - $WORKDIR/watch:/watch
    restart: always
